In [284]:
import pandas as pd
import numpy as np

In [285]:
df=pd.read_csv(r"C:\Users\gandj\OneDrive\Desktop\Case Study\NFL\Baker_DataFrame.csv")
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df['Cmp%']=round(df['Cmp']/df['Att']*100,2)
df['Avg_Yds']=round(df['Yds']/df['Cmp'],2)
df['Def-Rating']=round(abs((df['Int'] + df['Sk']))/df['Att'],2)*100
df=df[['Player','Tm','Cmp','Att','Cmp%','Avg_Yds','Yds','TD','Int','Sk','Def-Rating','Lng','Rate','Home Game','Opponent','Year','# TopReceiver','# TopRunningBacks']]
df.head()

,Player,Tm,Cmp,Att,Cmp%,Avg_Yds,Yds,TD,Int,Sk,Def-Rating,Lng,Rate,Home Game,Opponent,Year,# TopReceiver,# TopRunningBacks
0,Baker Mayfield,CLE,17,23,73.91,11.82,201,0,0,1,4.0,29.0,100.1,1,NYJ,2018,1,0.0
1,Baker Mayfield,CLE,21,41,51.22,14.05,295,2,2,2,10.0,59.0,70.7,0,OAK,2018,0,1.0
2,Baker Mayfield,CLE,25,43,58.14,13.68,342,1,1,5,14.0,39.0,81.7,1,BAL,2018,3,0.0
3,Baker Mayfield,CLE,22,46,47.83,10.82,238,1,2,5,15.0,32.0,52.6,1,LAC,2018,1,0.0
4,Baker Mayfield,CLE,23,34,67.65,9.35,215,2,0,5,15.0,23.0,104.4,0,TAM,2018,1,0.0

In [286]:
df2=pd.read_csv(r"C:\Users\gandj\OneDrive\Desktop\Case Study\NFL\Baker_DataFrame.csv")
df2.drop(['Unnamed: 0','Yds'], axis=1, inplace=True)
df2['Cmp%']=round(df['Cmp']/df['Att']*100,2)
df2['Avg_Yds']=round(df['Yds']/df['Cmp'],2)
df2['Def-Rating']=round(abs((df['Int'] + df['Sk']))/df['Att'],2)*100
df2=df2[['Opponent','Cmp','Att','Cmp%','Avg_Yds','TD','Int','Sk','Def-Rating','Lng','Rate',
                   'Home Game','# TopReceiver','# TopRunningBacks']]
df2.head()

,Opponent,Cmp,Att,Cmp%,Avg_Yds,TD,Int,Sk,Def-Rating,Lng,Rate,Home Game,# TopReceiver,# TopRunningBacks
0,NYJ,17,23,73.91,11.82,0,0,1,4.0,29.0,100.1,1,1,0.0
1,OAK,21,41,51.22,14.05,2,2,2,10.0,59.0,70.7,0,0,1.0
2,BAL,25,43,58.14,13.68,1,1,5,14.0,39.0,81.7,1,3,0.0
3,LAC,22,46,47.83,10.82,1,2,5,15.0,32.0,52.6,1,1,0.0
4,TAM,23,34,67.65,9.35,2,0,5,15.0,23.0,104.4,0,1,0.0

In [287]:
df2=df2.groupby(['Opponent','Home Game'])[['Cmp','Att','Cmp%','Avg_Yds','TD','Int','Sk',
                                   'Def-Rating','Lng','Rate','# TopReceiver','# TopRunningBacks']].mean().reset_index()
df2=df2[['Opponent','Cmp','Att','Cmp%','Avg_Yds','TD','Int','Sk','Def-Rating','Lng','Rate',
                   'Home Game','# TopReceiver','# TopRunningBacks']]
df2['# TopReceiver']=round(df2['# TopReceiver'],0)
df2['# TopRunningBacks']=round(df2['# TopRunningBacks'],0)
dummy_var=pd.get_dummies(df2, drop_first=True)
dummy_var['Opponent']=df2['Opponent']
dummy_var
#df2

,Cmp,Att,Cmp%,Avg_Yds,TD,Int,Sk,Def-Rating,Lng,Rate,...,Opponent_NYJ,Opponent_OAK,Opponent_PHI,Opponent_PIT,Opponent_SEA,Opponent_SFO,Opponent_TAM,Opponent_TEN,Opponent_WAS,Opponent
0,30.00,43.00,69.7700,8.230000,2.000000,1.00,1.000000,5.000000,26.000000,90.000000,...,0,0,0,0,0,0,0,0,0,ARI
1,20.50,32.00,64.4850,10.635000,1.500000,1.50,3.500000,16.000000,45.500000,82.150000,...,0,0,0,0,0,0,0,0,0,ARI
2,17.00,20.00,85.0000,12.710000,3.000000,0.00,0.000000,0.000000,28.000000,151.200000,...,0,0,0,0,0,0,0,0,0,ATL
3,20.50,37.00,55.9825,14.042500,1.500000,1.25,1.250000,6.750000,45.500000,81.475000,...,0,0,0,0,0,0,0,0,0,BAL
4,23.75,38.75,61.7675,11.042500,1.750000,1.00,1.250000,5.500000,35.750000,86.375000,...,0,0,0,0,0,0,0,0,0,BAL
5,26.00,38.00,68.4200,9.150000,2.000000,0.00,2.000000,5.000000,24.000000,102.700000,...,0,0,0,0,0,0,0,0,0,BUF
6,18.00,22.00,81.8200,13.220000,1.000000,0.00,1.000000,5.000000,66.000000,126.900000,...,0,0,0,0,0,0,0,0,0,CAR
7,19.00,31.00,61.2900,12.950000,1.000000,0.00,5.000000,16.000000,26.000000,97.000000,...,0,0,0,0,0,0,0,0,0,CHI
8,16.75,25.50,65.6900,16.475000,3.500000,1.00,2.000000,11.750000,43.750000,122.925000,...,0,0,0,0,0,0,0,0,0,CIN
9,18.00,28.00,62.7900,13.886667,1.666667,1.00,0.333333,5.333333,47.666667,90.466667,...,0,0,0,0,0,0,0,0,0,CIN
10,16.00,27.00,59.2600,14.690000,1.000000,1.00,4.000000,19.000000,75.000000,84.600000,...,0,0,0,0,0,0,0,0,0,CLE
11,19.00,30.00,63.3300,8.680000,2.000000,0.00,2.000000,7.000000,16.000000,100.000000,...,0,0,0,0,0,0,0,0,0,DAL
12,22.50,36.50,61.1750,10.275000,1.500000,0.50,2.000000,7.500000,36.000000,87.250000,...,0,0,0,0,0,0,0,0,0,DEN
13,24.00,28.00,85.7100,9.580000,2.000000,0.00,0.000000,0.000000,22.000000,124.700000,...,0,0,0,0,0,0,0,0,0,DEN
14,15.00,29.00,51.7200,11.730000,1.000000,2.00,1.000000,10.000000,37.000000,53.200000,...,0,0,0,0,0,0,0,0,0,DET
15,16.50,28.50,57.7350,9.910000,1.500000,2.50,5.000000,27.000000,29.000000,61.550000,...,0,0,0,0,0,0,0,0,0,GNB
16,29.00,43.00,67.4400,13.690000,1.000000,3.00,0.000000,7.000000,71.000000,75.400000,...,0,0,0,0,0,0,0,0,0,HOU
17,15.50,20.50,75.2400,11.105000,0.500000,0.50,1.500000,9.500000,27.000000,92.300000,...,0,0,0,0,0,0,0,0,0,HOU
18,21.00,37.00,56.7600,11.760000,2.000000,2.00,1.000000,8.000000,32.000000,72.700000,...,0,0,0,0,0,0,0,0,0,IND
19,19.00,29.00,65.5200,13.580000,2.000000,0.00,2.000000,7.000000,27.000000,116.700000,...,0,0,0,0,0,0,0,0,0,JAX
20,22.00,32.50,68.5800,12.080000,0.500000,1.00,1.500000,8.000000,35.500000,86.050000,...,0,0,0,0,0,0,0,0,0,KAN
21,29.00,42.00,69.0500,10.240000,2.000000,1.00,2.000000,7.000000,38.000000,95.000000,...,0,0,0,0,0,0,0,0,0,KAN
22,17.00,25.50,64.8850,12.630000,1.000000,0.00,2.000000,9.500000,55.000000,100.900000,...,0,0,0,0,0,0,0,0,0,LAC
23,22.00,46.00,47.8300,10.820000,1.000000,2.00,5.000000,15.000000,32.000000,52.600000,...,0,0,0,0,0,0,0,0,0,LAC
24,18.00,36.00,50.0000,10.830000,1.000000,1.00,3.000000,11.000000,30.000000,64.000000,...,0,0,0,0,0,0,0,0,0,LAR
25,12.00,25.00,48.0000,10.170000,0.000000,0.00,0.000000,0.000000,25.000000,62.400000,...,0,0,0,0,0,0,0,0,0,LVR
26,24.00,34.00,70.5900,13.620000,3.000000,1.00,1.000000,6.000000,37.000000,118.100000,...,0,0,0,0,0,0,0,0,0,MIA
27,15.00,33.00,45.4500,10.330000,0.000000,0.00,3.000000,9.000000,24.000000,59.500000,...,0,0,0,0,0,0,0,0,0,MIN
28,12.00,25.00,48.0000,14.170000,1.000000,0.00,3.000000,12.000000,67.000000,83.700000,...,0,0,0,0,0,0,0,0,0,NOR
29,15.50,26.00,58.4500,8.170000,1.000000,1.00,3.500000,16.500000,22.000000,67.700000,...,0,0,0,0,0,0,0,0,0,NWE
30,20.50,30.50,66.3300,10.680000,1.500000,0.00,1.500000,5.000000,25.500000,100.400000,...,0,0,0,0,0,0,0,0,0,NYG
31,23.50,44.00,53.5600,13.645000,0.500000,0.50,3.500000,9.500000,58.500000,76.050000,...,1,0,0,0,0,0,0,0,0,NYJ
32,17.00,23.00,73.9100,11.820000,0.000000,0.00,1.000000,4.000000,29.000000,100.100000,...,1,0,0,0,0,0,0,0,0,NYJ
33,21.00,41.00,51.2200,14.050000,2.000000,2.00,2.000000,10.000000,59.000000,70.700000,...,0,1,0,0,0,0,0,0,0,OAK
34,12.00,22.00,54.5500,17.000000,0.000000,0.00,3.000000,14.000000,43.000000,86.200000,...,0,0,1,0,0,0,0,0,0,PHI
35,17.40,31.60,55.3580,11.010000,1.800000,1.20,4.000000,17.800000,32.400000,75.180000,...,0,0,0,1,0,0,0,0,0,PIT
36,18.00,30.00,60.2000,11.376667,1.000000,0.00,3.000000,10.333333,36.000000,91.833333,...,0,0,0,1,0,0,0,0,0,PIT
37,13.00,26.00,50.0000,11.310000,0.000000,1.00,5.000000,23.000000,35.000000,51.300000,...,0,0,0,0,1,0,0,0,0,SEA
38,22.00,37.00,59.4600,11.320000,1.000000,3.00,0.000000,8.000000,41.000000,54.900000,...,0,0,0,0,1,0,0,0,0,SEA
39,8.00,22.00,36.3600,12.500000,0.000000,2.00,4.000000,27.000000,25.000000,13.400000,...,0,0,0,0,0,1,0,0,0,SFO
40,20.00,36.00,55.5600,10.750000,0.000000,1.00,4.000000,14.000000,32.000000,61.700000,...,0,0,0,0,0,1,0,0,0,SFO
41,23.00,34.00,67.6500,9.350000,2.000000,0.00,5.000000,15.000000,23.000000,104.400000,...,0,0,0,0,0,0,1,0,0,TAM
42,25.00,33.00,75.7600,13.360000,4.000000,0.00,0.000000,0.000000,75.000000,147.000000,...,0,0,0,0,0,0,0,1,0,TEN
43,25.00,38.00,65.7900,11.400000,1.000000,3.00,5.000000,21.000000,35.000000,64.000000,...,0,0,0,0,0,0,0,1,0,TEN
44,16.00,23.00,69.5700,9.750000,2.000000,0.00,2.000000,9.000000,18.000000,117.300000,...,0,0,0,0,0,0,0,0,1,WAS

We do not know how many attempts, complitions etc. Baker will have as the starting QB in Tampa, therefore we will take the average of the X features corrosponding to the teams that Baker will face this season.

In [288]:
opp_perf=df.groupby(['Opponent','Home Game'])[['Cmp','Att','Cmp%','Avg_Yds','TD','Int','Sk',
                                   'Def-Rating','Lng','Rate','# TopReceiver','# TopRunningBacks']].mean().reset_index()
opp_perf=opp_perf[['Opponent','Cmp','Att','Cmp%','Avg_Yds','TD','Int','Sk','Def-Rating','Lng','Rate',
                   'Home Game','# TopReceiver','# TopRunningBacks']]
opp_perf['# TopReceiver']=round(opp_perf['# TopReceiver'],0)
opp_perf['# TopRunningBacks']=round(opp_perf['# TopRunningBacks'],0)
#opp_perf['dummy_var']=opp_perf['Opponent'].apply(lambda x: np.asarray(team_dic[x]))
opp_perf=opp_perf.merge(dummy_var,on='Opponent',how='left')
opp_perf=opp_perf[['Opponent', 'Cmp_x', 'Att_x', 'Cmp%_x', 'Avg_Yds_x', 'TD_x', 'Int_x','Sk_x', 'Def-Rating_x', 'Lng_x', 'Rate_x', 'Home Game_x','# TopReceiver_x', '# TopRunningBacks_x','Opponent_ATL','Opponent_BAL', 'Opponent_BUF', 'Opponent_CAR', 'Opponent_CHI','Opponent_CIN', 'Opponent_CLE', 'Opponent_DAL', 'Opponent_DEN','Opponent_DET', 'Opponent_GNB', 'Opponent_HOU', 'Opponent_IND','Opponent_JAX', 'Opponent_KAN', 'Opponent_LAC', 'Opponent_LAR','Opponent_LVR', 'Opponent_MIA', 'Opponent_MIN', 'Opponent_NOR','Opponent_NWE', 'Opponent_NYG', 'Opponent_NYJ', 'Opponent_OAK','Opponent_PHI', 'Opponent_PIT', 'Opponent_SEA', 'Opponent_SFO','Opponent_TAM', 'Opponent_TEN', 'Opponent_WAS']]
opp_perf=opp_perf.rename(columns={'Cmp_x':'Cmp', 'Att_x':'Att', 'Cmp%_x':'Cmp%', 'Avg_Yds_x':'Avg_Yds', 'TD_x':'TD', 'Int_x':'Int','Sk_x':'Sk', 'Def-Rating_x':'Def-Rating', 'Lng_x':'Lng', 'Rate_x':'Rate', 'Home Game_x':'Home Game',
                                 '# TopReceiver_x':'# TopReceiver', '# TopRunningBacks_x':'# TopRunningBacks'})
opp_perf=opp_perf.drop_duplicates()
opp_perf

,Opponent,Cmp,Att,Cmp%,Avg_Yds,TD,Int,Sk,Def-Rating,Lng,...,Opponent_NYG,Opponent_NYJ,Opponent_OAK,Opponent_PHI,Opponent_PIT,Opponent_SEA,Opponent_SFO,Opponent_TAM,Opponent_TEN,Opponent_WAS
0,ARI,30.00,43.00,69.7700,8.230000,2.000000,1.00,1.000000,5.000000,26.000000,...,0,0,0,0,0,0,0,0,0,0
2,ARI,20.50,32.00,64.4850,10.635000,1.500000,1.50,3.500000,16.000000,45.500000,...,0,0,0,0,0,0,0,0,0,0
4,ATL,17.00,20.00,85.0000,12.710000,3.000000,0.00,0.000000,0.000000,28.000000,...,0,0,0,0,0,0,0,0,0,0
5,BAL,20.50,37.00,55.9825,14.042500,1.500000,1.25,1.250000,6.750000,45.500000,...,0,0,0,0,0,0,0,0,0,0
7,BAL,23.75,38.75,61.7675,11.042500,1.750000,1.00,1.250000,5.500000,35.750000,...,0,0,0,0,0,0,0,0,0,0
9,BUF,26.00,38.00,68.4200,9.150000,2.000000,0.00,2.000000,5.000000,24.000000,...,0,0,0,0,0,0,0,0,0,0
10,CAR,18.00,22.00,81.8200,13.220000,1.000000,0.00,1.000000,5.000000,66.000000,...,0,0,0,0,0,0,0,0,0,0
11,CHI,19.00,31.00,61.2900,12.950000,1.000000,0.00,5.000000,16.000000,26.000000,...,0,0,0,0,0,0,0,0,0,0
12,CIN,16.75,25.50,65.6900,16.475000,3.500000,1.00,2.000000,11.750000,43.750000,...,0,0,0,0,0,0,0,0,0,0
14,CIN,18.00,28.00,62.7900,13.886667,1.666667,1.00,0.333333,5.333333,47.666667,...,0,0,0,0,0,0,0,0,0,0
16,CLE,16.00,27.00,59.2600,14.690000,1.000000,1.00,4.000000,19.000000,75.000000,...,0,0,0,0,0,0,0,0,0,0
17,DAL,19.00,30.00,63.3300,8.680000,2.000000,0.00,2.000000,7.000000,16.000000,...,0,0,0,0,0,0,0,0,0,0
18,DEN,22.50,36.50,61.1750,10.275000,1.500000,0.50,2.000000,7.500000,36.000000,...,0,0,0,0,0,0,0,0,0,0
20,DEN,24.00,28.00,85.7100,9.580000,2.000000,0.00,0.000000,0.000000,22.000000,...,0,0,0,0,0,0,0,0,0,0
22,DET,15.00,29.00,51.7200,11.730000,1.000000,2.00,1.000000,10.000000,37.000000,...,0,0,0,0,0,0,0,0,0,0
23,GNB,16.50,28.50,57.7350,9.910000,1.500000,2.50,5.000000,27.000000,29.000000,...,0,0,0,0,0,0,0,0,0,0
24,HOU,29.00,43.00,67.4400,13.690000,1.000000,3.00,0.000000,7.000000,71.000000,...,0,0,0,0,0,0,0,0,0,0
26,HOU,15.50,20.50,75.2400,11.105000,0.500000,0.50,1.500000,9.500000,27.000000,...,0,0,0,0,0,0,0,0,0,0
28,IND,21.00,37.00,56.7600,11.760000,2.000000,2.00,1.000000,8.000000,32.000000,...,0,0,0,0,0,0,0,0,0,0
29,JAX,19.00,29.00,65.5200,13.580000,2.000000,0.00,2.000000,7.000000,27.000000,...,0,0,0,0,0,0,0,0,0,0
30,KAN,22.00,32.50,68.5800,12.080000,0.500000,1.00,1.500000,8.000000,35.500000,...,0,0,0,0,0,0,0,0,0,0
32,KAN,29.00,42.00,69.0500,10.240000,2.000000,1.00,2.000000,7.000000,38.000000,...,0,0,0,0,0,0,0,0,0,0
34,LAC,17.00,25.50,64.8850,12.630000,1.000000,0.00,2.000000,9.500000,55.000000,...,0,0,0,0,0,0,0,0,0,0
36,LAC,22.00,46.00,47.8300,10.820000,1.000000,2.00,5.000000,15.000000,32.000000,...,0,0,0,0,0,0,0,0,0,0
38,LAR,18.00,36.00,50.0000,10.830000,1.000000,1.00,3.000000,11.000000,30.000000,...,0,0,0,0,0,0,0,0,0,0
39,LVR,12.00,25.00,48.0000,10.170000,0.000000,0.00,0.000000,0.000000,25.000000,...,0,0,0,0,0,0,0,0,0,0
40,MIA,24.00,34.00,70.5900,13.620000,3.000000,1.00,1.000000,6.000000,37.000000,...,0,0,0,0,0,0,0,0,0,0
41,MIN,15.00,33.00,45.4500,10.330000,0.000000,0.00,3.000000,9.000000,24.000000,...,0,0,0,0,0,0,0,0,0,0
42,NOR,12.00,25.00,48.0000,14.170000,1.000000,0.00,3.000000,12.000000,67.000000,...,0,0,0,0,0,0,0,0,0,0
43,NWE,15.50,26.00,58.4500,8.170000,1.000000,1.00,3.500000,16.500000,22.000000,...,0,0,0,0,0,0,0,0,0,0
44,NYG,20.50,30.50,66.3300,10.680000,1.500000,0.00,1.500000,5.000000,25.500000,...,1,0,0,0,0,0,0,0,0,0
45,NYJ,23.50,44.00,53.5600,13.645000,0.500000,0.50,3.500000,9.500000,58.500000,...,0,1,0,0,0,0,0,0,0,0
47,NYJ,17.00,23.00,73.9100,11.820000,0.000000,0.00,1.000000,4.000000,29.000000,...,0,1,0,0,0,0,0,0,0,0
49,OAK,21.00,41.00,51.2200,14.050000,2.000000,2.00,2.000000,10.000000,59.000000,...,0,0,1,0,0,0,0,0,0,0
50,PHI,12.00,22.00,54.5500,17.000000,0.000000,0.00,3.000000,14.000000,43.000000,...,0,0,0,1,0,0,0,0,0,0
51,PIT,17.40,31.60,55.3580,11.010000,1.800000,1.20,4.000000,17.800000,32.400000,...,0,0,0,0,1,0,0,0,0,0
53,PIT,18.00,30.00,60.2000,11.376667,1.000000,0.00,3.000000,10.333333,36.000000,...,0,0,0,0,1,0,0,0,0,0
55,SEA,13.00,26.00,50.0000,11.310000,0.000000,1.00,5.000000,23.000000,35.000000,...,0,0,0,0,0,1,0,0,0,0
57,SEA,22.00,37.00,59.4600,11.320000,1.000000,3.00,0.000000,8.000000,41.000000,...,0,0,0,0,0,1,0,0,0,0
59,SFO,8.00,22.00,36.3600,12.500000,0.000000,2.00,4.000000,27.000000,25.000000,...,0,0,0,0,0,0,1,0,0,0
61,SFO,20.00,36.00,55.5600,10.750000,0.000000,1.00,4.000000,14.000000,32.000000,...,0,0,0,0,0,0,1,0,0,0
63,TAM,23.00,34.00,67.6500,9.350000,2.000000,0.00,5.000000,15.000000,23.000000,...,0,0,0,0,0,0,0,1,0,0
64,TEN,25.00,33.00,75.7600,13.360000,4.000000,0.00,0.000000,0.000000,75.000000,...,0,0,0,0,0,0,0,0,1,0
66,TEN,25.00,38.00,65.7900,11.400000,1.000000,3.00,5.000000,21.000000,35.000000,...,0,0,0,0,0,0,0,0,1,0
68,WAS,16.00,23.00,69.5700,9.750000,2.000000,0.00,2.000000,9.000000,18.000000,...,0,0,0,0,0,0,0,0,0,1

In [289]:
schedule=pd.read_html('https://www.pro-football-reference.com/years/2023/games.htm')[0]
schedule['RoadTeam']=schedule['Winner/tie']
schedule['HomeTeam']=schedule['Loser/tie']
schedule.head()

,Week,Day,Date,Time,Winner/tie,Unnamed: 5,Loser/tie,Unnamed: 7,PtsW,PtsL,YdsW,TOW,YdsL,TOL,RoadTeam,HomeTeam
0,1,Thu,2023-09-07,8:20PM,Detroit Lions,@,Kansas City Chiefs,boxscore,21,20,368,1,316,1,Detroit Lions,Kansas City Chiefs
1,1,Sun,2023-09-10,1:00PM,Carolina Panthers,@,Atlanta Falcons,preview,NaN,NaN,NaN,NaN,NaN,NaN,Carolina Panthers,Atlanta Falcons
2,1,Sun,2023-09-10,1:00PM,Cincinnati Bengals,@,Cleveland Browns,preview,NaN,NaN,NaN,NaN,NaN,NaN,Cincinnati Bengals,Cleveland Browns
3,1,Sun,2023-09-10,1:00PM,Arizona Cardinals,@,Washington Commanders,preview,NaN,NaN,NaN,NaN,NaN,NaN,Arizona Cardinals,Washington Commanders
4,1,Sun,2023-09-10,1:00PM,Houston Texans,@,Baltimore Ravens,preview,NaN,NaN,NaN,NaN,NaN,NaN,Houston Texans,Baltimore Ravens

In [290]:
schedule[(schedule['HomeTeam']=='Tampa Bay Buccaneers') | (schedule['RoadTeam']=='Tampa Bay Buccaneers')]

,Week,Day,Date,Time,Winner/tie,Unnamed: 5,Loser/tie,Unnamed: 7,PtsW,PtsL,YdsW,TOW,YdsL,TOL,RoadTeam,HomeTeam
8,1,Sun,2023-09-10,1:00PM,Tampa Bay Buccaneers,@,Minnesota Vikings,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tampa Bay Buccaneers,Minnesota Vikings
18,2,Sun,2023-09-17,1:00PM,Chicago Bears,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Chicago Bears,Tampa Bay Buccaneers
48,3,Mon,2023-09-25,7:15PM,Philadelphia Eagles,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Philadelphia Eagles,Tampa Bay Buccaneers
60,4,Sun,2023-10-01,1:00PM,Tampa Bay Buccaneers,@,New Orleans Saints,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tampa Bay Buccaneers,New Orleans Saints
87,6,Sun,2023-10-15,1:00PM,Detroit Lions,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Detroit Lions,Tampa Bay Buccaneers
100,7,Sun,2023-10-22,1:00PM,Atlanta Falcons,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Atlanta Falcons,Tampa Bay Buccaneers
113,8,Thu,2023-10-26,8:15PM,Tampa Bay Buccaneers,@,Buffalo Bills,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tampa Bay Buccaneers,Buffalo Bills
137,9,Sun,2023-11-05,1:00PM,Tampa Bay Buccaneers,@,Houston Texans,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tampa Bay Buccaneers,Houston Texans
151,10,Sun,2023-11-12,1:00PM,Tennessee Titans,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tennessee Titans,Tampa Bay Buccaneers
169,11,Sun,2023-11-19,4:05PM,Tampa Bay Buccaneers,@,San Francisco 49ers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tampa Bay Buccaneers,San Francisco 49ers
184,12,Sun,2023-11-26,1:00PM,Tampa Bay Buccaneers,@,Indianapolis Colts,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tampa Bay Buccaneers,Indianapolis Colts
194,13,Sun,2023-12-03,1:00PM,Carolina Panthers,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Carolina Panthers,Tampa Bay Buccaneers
213,14,Sun,2023-12-10,1:00PM,Tampa Bay Buccaneers,@,Atlanta Falcons,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tampa Bay Buccaneers,Atlanta Falcons
231,15,Sun,2023-12-17,1:00PM,Tampa Bay Buccaneers,@,Green Bay Packers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tampa Bay Buccaneers,Green Bay Packers
248,16,Sun,2023-12-24,4:05PM,Jacksonville Jaguars,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Jacksonville Jaguars,Tampa Bay Buccaneers
262,17,Sun,2023-12-31,1:00PM,New Orleans Saints,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,New Orleans Saints,Tampa Bay Buccaneers
288,18,Sun,2024-01-07,1:00PM,Tampa Bay Buccaneers,@,Carolina Panthers,preview,NaN,NaN,NaN,NaN,NaN,NaN,Tampa Bay Buccaneers,Carolina Panthers

In [291]:
name_switch={'Kansas City Chiefs':'KAN', 'Atlanta Falcons':'ATL', 'Cleveland Browns':'CLE',
       'Indianapolis Colts':'IND', 'Minnesota Vikings':'MIN', 'New Orleans Saints':'NOR',
       'Pittsburgh Steelers':'PIT', 'Baltimore Ravens':'BAL', 'Washington Commanders':'WAS',
       'Chicago Bears':'CHI', 'Denver Broncos':'DEN', 'New England Patriots':'NWE',
       'Los Angeles Chargers':'LAC', 'Seattle Seahawks':'SEA', 'New York Giants':'NYG',
       'New York Jets':'NYJ', 'Philadelphia Eagles':'PHI', 'Buffalo Bills':'BUF',
       'Cincinnati Bengals':'CIN', 'Detroit Lions':'DET', 'Houston Texans':'HOU',
       'Jacksonville Jaguars':'JAX', 'Tennessee Titans':'TEN', 'Tampa Bay Buccaneers':'TAM',
       'Arizona Cardinals':'ARI', 'Los Angeles Rams':'LAR', 'Dallas Cowboys':'DAL',
       'Carolina Panthers':'CAR', 'San Francisco 49ers':'SFO', 'Green Bay Packers':'GNB',
       'Miami Dolphins':'MIA', 'Las Vegas Raiders':'LVR'}

In [292]:
name_switch['Indianapolis Colts']

'IND'

In [293]:
bakers_schedule=schedule[(schedule['HomeTeam']=='Tampa Bay Buccaneers') | (schedule['RoadTeam']=='Tampa Bay Buccaneers')]
#bakers_schedule=bakers_schedule.iloc[3:,:]
bakers_schedule['HomeTeam']=bakers_schedule['HomeTeam'].replace(name_switch)
bakers_schedule['HomeTeam']=bakers_schedule['HomeTeam'].astype(str)
bakers_schedule['RoadTeam']=bakers_schedule['RoadTeam'].replace(name_switch)
bakers_schedule['RoadTeam']=bakers_schedule['RoadTeam'].astype(str)
bakers_schedule['Week']=bakers_schedule['Week'].astype(int)
bakers_schedule['Home_Game']=np.where(bakers_schedule['HomeTeam']=='TAM',1,0)
bakers_schedule['Home_Game']=bakers_schedule['Home_Game'].apply(lambda x: 'Home Game' if x ==1 else 'Road Game')
bakers_schedule.iloc[-1,:]=[5,'bye','bye','bye','bye','bye','bye','bye','bye','bye','bye','bye','bye','bye','bye','bye','bye']
bakers_schedule=bakers_schedule.sort_values('Week', ascending=True)
bakers_schedule[' ']=range(1,18)
bakers_schedule=bakers_schedule.set_index(' ')
bakers_schedule

C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\989621260.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bakers_schedule['HomeTeam']=bakers_schedule['HomeTeam'].replace(name_switch)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\989621260.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bakers_schedule['HomeTeam']=bakers_schedule['HomeTeam'].astype(str)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\989621260.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bakers_schedule['RoadTeam']=bakers_schedule['RoadTeam'].replace(name_switch)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\989621260.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bakers_schedule['RoadTeam']=bakers_schedule['RoadTeam'].astype(str)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\989621260.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bakers_schedule['Week']=bakers_schedule['Week'].astype(int)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\989621260.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bakers_schedule['Home_Game']=np.where(bakers_schedule['HomeTeam']=='TAM',1,0)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\989621260.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bakers_schedule['Home_Game']=bakers_schedule['Home_Game'].apply(lambda x: 'Home Game' if x ==1 else 'Road Game')

,Week,Day,Date,Time,Winner/tie,Unnamed: 5,Loser/tie,Unnamed: 7,PtsW,PtsL,YdsW,TOW,YdsL,TOL,RoadTeam,HomeTeam,Home_Game
,,,,,,,,,,,,,,,,,
1,1.0,Sun,2023-09-10,1:00PM,Tampa Bay Buccaneers,@,Minnesota Vikings,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,MIN,Road Game
2,2.0,Sun,2023-09-17,1:00PM,Chicago Bears,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,CHI,TAM,Home Game
3,3.0,Mon,2023-09-25,7:15PM,Philadelphia Eagles,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,PHI,TAM,Home Game
4,4.0,Sun,2023-10-01,1:00PM,Tampa Bay Buccaneers,@,New Orleans Saints,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,NOR,Road Game
5,5.0,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye
6,6.0,Sun,2023-10-15,1:00PM,Detroit Lions,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,DET,TAM,Home Game
7,7.0,Sun,2023-10-22,1:00PM,Atlanta Falcons,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,ATL,TAM,Home Game
8,8.0,Thu,2023-10-26,8:15PM,Tampa Bay Buccaneers,@,Buffalo Bills,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,BUF,Road Game
9,9.0,Sun,2023-11-05,1:00PM,Tampa Bay Buccaneers,@,Houston Texans,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,HOU,Road Game
10,10.0,Sun,2023-11-12,1:00PM,Tennessee Titans,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,TEN,TAM,Home Game
11,11.0,Sun,2023-11-19,4:05PM,Tampa Bay Buccaneers,@,San Francisco 49ers,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,SFO,Road Game
12,12.0,Sun,2023-11-26,1:00PM,Tampa Bay Buccaneers,@,Indianapolis Colts,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,IND,Road Game
13,13.0,Sun,2023-12-03,1:00PM,Carolina Panthers,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,CAR,TAM,Home Game
14,14.0,Sun,2023-12-10,1:00PM,Tampa Bay Buccaneers,@,Atlanta Falcons,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,ATL,Road Game
15,15.0,Sun,2023-12-17,1:00PM,Tampa Bay Buccaneers,@,Green Bay Packers,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,GNB,Road Game
16,16.0,Sun,2023-12-24,4:05PM,Jacksonville Jaguars,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,JAX,TAM,Home Game
17,17.0,Sun,2023-12-31,1:00PM,New Orleans Saints,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,NOR,TAM,Home Game

In [294]:
bakers_schedule.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17 entries, 1 to 17
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Week        17 non-null     float64
 1   Day         17 non-null     object
 2   Date        17 non-null     object
 3   Time        17 non-null     object
 4   Winner/tie  17 non-null     object
 5   Unnamed: 5  17 non-null     object
 6   Loser/tie   17 non-null     object
 7   Unnamed: 7  17 non-null     object
 8   PtsW        1 non-null      object
 9   PtsL        1 non-null      object
 10  YdsW        1 non-null      object
 11  TOW         1 non-null      object
 12  YdsL        1 non-null      object
 13  TOL         1 non-null      object
 14  RoadTeam    17 non-null     object
 15  HomeTeam    17 non-null     object
 16  Home_Game   17 non-null     object
dtypes: float64(1), object(16)
memory usage: 2.4+ KB

In [295]:
import joblib

col_names=joblib.load(r"C:\Users\gandj\OneDrive\Desktop\Case Study\NFL\col_names.pkl")
col_names

['Cmp',
 'Att',
 'Cmp%',
 'Avg_Yds',
 'TD',
 'Int',
 'Sk',
 'Def-Rating',
 'Lng',
 'Rate',
 'Home Game',
 '# TopReceiver',
 '# TopRunningBacks',
 'Opponent_ATL',
 'Opponent_BAL',
 'Opponent_BUF',
 'Opponent_CAR',
 'Opponent_CHI',
 'Opponent_CIN',
 'Opponent_CLE',
 'Opponent_DAL',
 'Opponent_DEN',
 'Opponent_DET',
 'Opponent_GNB',
 'Opponent_HOU',
 'Opponent_IND',
 'Opponent_JAX',
 'Opponent_KAN',
 'Opponent_LAC',
 'Opponent_LAR',
 'Opponent_LVR',
 'Opponent_MIA',
 'Opponent_MIN',
 'Opponent_NOR',
 'Opponent_NWE',
 'Opponent_NYG',
 'Opponent_NYJ',
 'Opponent_OAK',
 'Opponent_PHI',
 'Opponent_PIT',
 'Opponent_SEA',
 'Opponent_SFO',
 'Opponent_TAM',
 'Opponent_TEN',
 'Opponent_WAS']

In [296]:
len(opp_perf.columns[1:])

45

In [297]:
if bakers_schedule[(bakers_schedule['RoadTeam']=='TAM') & (bakers_schedule['Week']==2)]['RoadTeam'].get(key=2):
    y=str(bakers_schedule[bakers_schedule['Week']==2]['HomeTeam'].get(key=2))
else:
    y=str(bakers_schedule[bakers_schedule['Week']==2]['RoadTeam'].get(key=2))

if bakers_schedule[(bakers_schedule['RoadTeam']=='TAM') & (bakers_schedule['Week']==2)]['Home_Game'].get(key=2):
    type_of_game=0
else:
    type_of_game=1

cmp=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Cmp'].get(key=0)
att=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Att'].get(key=0)
cmp_per=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Cmp%'].get(key=0)
avg_yds=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Avg_Yds'].get(key=0)
td=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['TD'].get(key=0)
int=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Int'].get(key=0)
sk=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Sk'].get(key=0)
def_rat=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Def-Rating'].get(key=0)
lng=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Lng'].get(key=0)
rate=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Rate'].get(key=0)
home=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Home Game'].get(key=0)
wr=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['# TopReceiver'].get(key=0)
rb=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['# TopRunningBacks'].get(key=0)
atl=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_ATL'].get(key=0)
bal=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_BAL'].get(key=0)
buf=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_BUF'].get(key=0)
car=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_CAR'].get(key=0)
chi=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_CHI'].get(key=0)
cin=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_CIN'].get(key=0)
cle=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_CLE'].get(key=0)
dal=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_DAL'].get(key=0)
den=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_DEN'].get(key=0)
det=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_DET'].get(key=0)
gnb=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_GNB'].get(key=0)
hou=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_HOU'].get(key=0)
ind=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_IND'].get(key=0)
jax=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_JAX'].get(key=0)
kan=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_KAN'].get(key=0)
lac=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_LAC'].get(key=0)
lar=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_LAR'].get(key=0)
lvr=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_LVR'].get(key=0)
mia=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_MIA'].get(key=0)
min=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_MIN'].get(key=0)
nor=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_NOR'].get(key=0)
nwe=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_NWE'].get(key=0)
nyg=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_NYG'].get(key=0)
nyj=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_NYJ'].get(key=0)
oak=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_OAK'].get(key=0)
phi=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_PHI'].get(key=0)
pit=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_PIT'].get(key=0)
sea=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_SEA'].get(key=0)
sfo=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_SFO'].get(key=0)
tam=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_TAM'].get(key=0)
ten=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_TEN'].get(key=0)
was=opp_perf[(opp_perf['Opponent']==str(y)) & (opp_perf['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_WAS'].get(key=0)

output=[cmp,att,cmp_per,avg_yds,td,int,sk,def_rat,lng,rate,home,wr,rb,atl,bal,buf,car,chi,cin,cle,dal,den,det,gnb,hou,ind,jax,kan,lac,lar,lvr,mia,min,nor,nwe,nyg,nyj,oak,phi,pit,sea,sfo,tam,ten,was]
np.array(output).reshape(1,-1)

array([[19.  , 31.  , 61.29, 12.95,  1.  ,  0.  ,  5.  , 16.  , 26.  ,
        97.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ]])

In [298]:
def x_features(x,team,week,y):
  if x[(x['RoadTeam']==team) & (x['Week']==week)]['RoadTeam'].get(key=week):
      opp=str(x[x['Week']==week]['HomeTeam'].get(key=week))
  else:
      opp=str(x[x['Week']==week]['RoadTeam'].get(key=week))

  if x[(x['RoadTeam']==team) & (x['Week']==week)]['Home_Game'].get(key=week):
      type_of_game=0
  else:
      type_of_game=1



  cmp=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Cmp'].get(key=0)
  att=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Att'].get(key=0)
  cmp_per=y[(opp_perf['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Cmp%'].get(key=0)
  avg_yds=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Avg_Yds'].get(key=0)
  td=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['TD'].get(key=0)
  int=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Int'].get(key=0)
  sk=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Sk'].get(key=0)
  def_rat=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Def-Rating'].get(key=0)
  lng=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Lng'].get(key=0)
  rate=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Rate'].get(key=0)
  home=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Home Game'].get(key=0)
  wr=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['# TopReceiver'].get(key=0)
  rb=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['# TopRunningBacks'].get(key=0)
  atl=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_ATL'].get(key=0)
  bal=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_BAL'].get(key=0)
  buf=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_BUF'].get(key=0)
  car=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_CAR'].get(key=0)
  chi=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_CHI'].get(key=0)
  cin=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_CIN'].get(key=0)
  cle=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_CLE'].get(key=0)
  dal=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_DAL'].get(key=0)
  den=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_DEN'].get(key=0)
  det=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_DET'].get(key=0)
  gnb=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_GNB'].get(key=0)
  hou=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_HOU'].get(key=0)
  ind=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_IND'].get(key=0)
  jax=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_JAX'].get(key=0)
  kan=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_KAN'].get(key=0)
  lac=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_LAC'].get(key=0)
  lar=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_LAR'].get(key=0)
  lvr=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_LVR'].get(key=0)
  mia=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_MIA'].get(key=0)
  min=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_MIN'].get(key=0)
  nor=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_NOR'].get(key=0)
  nwe=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_NWE'].get(key=0)
  nyg=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_NYG'].get(key=0)
  nyj=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_NYJ'].get(key=0)
  oak=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_OAK'].get(key=0)
  phi=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_PHI'].get(key=0)
  pit=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_PIT'].get(key=0)
  sea=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_SEA'].get(key=0)
  sfo=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_SFO'].get(key=0)
  tam=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_TAM'].get(key=0)
  ten=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_TEN'].get(key=0)
  was=y[(y['Opponent']==str(opp)) & (y['Home Game']==type_of_game)].reset_index().drop(['index','Opponent'],axis=1)['Opponent_WAS'].get(key=0)

  output=[cmp,att,cmp_per,avg_yds,td,int,sk,def_rat,lng,rate,home,wr,rb,atl,bal,buf,car,chi,cin,cle,dal,den,det,gnb,hou,ind,jax,kan,lac,lar,lvr,mia,min,nor,nwe,nyg,nyj,oak,phi,pit,sea,sfo,tam,ten,was]
  return np.array(output).reshape(1,-1)

In [299]:
final_model=joblib.load(r"C:\Users\gandj\OneDrive\Desktop\Case Study\NFL\Baker's_Passing_Performance_2023.pkl")
final_model

RandomizedSearchCV(cv=KFold(n_splits=10, random_state=101, shuffle=True),
                   error_score='raise', estimator=ElasticNet(random_state=101),
                   n_iter=1000,
                   param_distributions={'alpha': array([1.000e-04, 1.020e-02, 2.030e-02, 3.040e-02, 4.050e-02, 5.060e-02,
       6.070e-02, 7.080e-02, 8.090e-02, 9.100e-02, 1.011e-01, 1.112e-01,
       1.213e-01, 1.314e-01, 1.415e-01, 1.516e-01, 1.617e-01, 1....
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
                                        'max_iter': [1000, 10000, 100000],
                                        'precompute': [True, False],
                                        'selection': ['cyclic', 'random'],
                                        'tol': array([4.00000000e-04, 1.11466667e-01, 2.22533333e-01, 3.33600000e-01,
       4.44666667e-01, 5.55733333e-01, 6.66800000e-01, 7.77866667e-01,
       8.88933333e-01, 1.00000000e+00])},
                   random_state=101, return_train_score=True,
                   scoring='neg_root_mean_squared_error')

In [300]:
x_features(bakers_schedule,'TAM',4,opp_perf)

array([[None, None, None, None, None, None, None, None, None, None, None,
        None, None, None, None, None, None, None, None, None, None, None,
        None, None, None, None, None, None, None, None, None, None, None,
        None, None, None, None, None, None, None, None, None, None, None,
        None]], dtype=object)

In [301]:
# here we check if we have NaN values which have been generated through the for loop
# as we can see Week 4,5,8,12,14 and 16 generated NaN, this is because Baker never played against this team at home,
## on the road or at all
lst=[]
for x in range(1,18):
    lst.append(print("X features for Week {}: ".format(x),x_features(bakers_schedule,'TAM',x,opp_perf),"\n"))
lst

X features for Week 1:  [[15.   33.   45.45 10.33  0.    0.    3.    9.   24.   59.5   0.    0.
   1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    1.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]

X features for Week 2:  [[19.   31.   61.29 12.95  1.    0.    5.   16.   26.   97.    1.    1.
   0.    0.    0.    0.    0.    1.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]

X features for Week 3:  [[12.   22.   54.55 17.    0.    0.    3.   14.   43.   86.2   1.    0.
   1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    1.    0.    0.    0.    0.    0.    0.  ]]

X features for Week 4:  [[None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None]]

X features for Week 5:  [[None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None]]

X features for Week 6:  [[15.   29.   51.72 11.73  1.    2.    1.   10.   37.   53.2   1.    0.
   1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    1.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]

X features for Week 7:  [[ 17.    20.    85.    12.71   3.     0.     0.     0.    28.   151.2
    1.     0.     1.     1.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.  ]]

X features for Week 8:  [[None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None]]

X features for Week 9:  [[29.   43.   67.44 13.69  1.    3.    0.    7.   71.   75.4   0.    2.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]

X features for Week 10:  [[25.   38.   65.79 11.4   1.    3.    5.   21.   35.   64.    1.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    1.    0.  ]]

X features for Week 11:  [[ 8.   22.   36.36 12.5   0.    2.    4.   27.   25.   13.4   0.    1.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    1.    0.    0.    0.  ]]

X features for Week 12:  [[None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None]]

X features for Week 13:  [[ 18.    22.    81.82  13.22   1.     0.     1.     5.    66.   126.9
    1.     1.     0.     0.     0.     0.     1.     0.     0.     0.
    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.  ]]

X features for Week 14:  [[None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None]]

X features for Week 15:  [[16.5   28.5   57.735  9.91   1.5    2.5    5.    27.    29.    61.55
   0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.     0.     0.     1.     0.     0.     0.     0.     0.     0.
   0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
   0.     0.     0.     0.     0.   ]]

X features for Week 16:  [[None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None None None None None None None None None None None None
  None None None]]

X features for Week 17:  [[12.   25.   48.   14.17  1.    0.    3.   12.   67.   83.7   1.    1.
   1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    1.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [302]:
bakers_schedule[(bakers_schedule['Week']==4) | (bakers_schedule['Week']==5) | (bakers_schedule['Week']==8) |
                (bakers_schedule['Week']==12) | (bakers_schedule['Week']==14) | (bakers_schedule['Week']==16)][['RoadTeam',
                'HomeTeam', 'Home_Game']]

   RoadTeam HomeTeam  Home_Game

4       TAM      NOR  Road Game
5       bye      bye        bye
8       TAM      BUF  Road Game
12      TAM      IND  Road Game
14      TAM      ATL  Road Game
16      JAX      TAM  Home Game

In [303]:
print(opp_perf.columns)
print(len(opp_perf))

Index(['Opponent', 'Cmp', 'Att', 'Cmp%', 'Avg_Yds', 'TD', 'Int', 'Sk',
       'Def-Rating', 'Lng', 'Rate', 'Home Game', '# TopReceiver',
       '# TopRunningBacks', 'Opponent_ATL', 'Opponent_BAL', 'Opponent_BUF',
       'Opponent_CAR', 'Opponent_CHI', 'Opponent_CIN', 'Opponent_CLE',
       'Opponent_DAL', 'Opponent_DEN', 'Opponent_DET', 'Opponent_GNB',
       'Opponent_HOU', 'Opponent_IND', 'Opponent_JAX', 'Opponent_KAN',
       'Opponent_LAC', 'Opponent_LAR', 'Opponent_LVR', 'Opponent_MIA',
       'Opponent_MIN', 'Opponent_NOR', 'Opponent_NWE', 'Opponent_NYG',
       'Opponent_NYJ', 'Opponent_OAK', 'Opponent_PHI', 'Opponent_PIT',
       'Opponent_SEA', 'Opponent_SFO', 'Opponent_TAM', 'Opponent_TEN',
       'Opponent_WAS'],
      dtype='object')
45

In [304]:
atl=opp_perf[(opp_perf['Opponent']=='ATL') & (opp_perf['Home Game']==1)]
atl['Home Game'].replace({1:0}, inplace=True)
opp_perf=opp_perf.append(atl)

buf=opp_perf[(opp_perf['Opponent']=='BUF') & (opp_perf['Home Game']==1)]
buf['Home Game'].replace({1:0}, inplace=True)
opp_perf=opp_perf.append(buf)

ind=opp_perf[(opp_perf['Opponent']=='IND') & (opp_perf['Home Game']==1)]
ind['Home Game'].replace({1:0}, inplace=True)
opp_perf=opp_perf.append(ind)

nor=opp_perf[(opp_perf['Opponent']=='NOR') & (opp_perf['Home Game']==1)]
nor['Home Game'].replace({1:0}, inplace=True)
opp_perf=opp_perf.append(nor)

jax=opp_perf[(opp_perf['Opponent']=='JAX') & (opp_perf['Home Game']==0)]
jax['Home Game'].replace({0:1}, inplace=True)
opp_perf=opp_perf.append(jax)

opp_perf.sort_values(by='Opponent')

C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atl['Home Game'].replace({1:0}, inplace=True)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  opp_perf=opp_perf.append(atl)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  buf['Home Game'].replace({1:0}, inplace=True)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  opp_perf=opp_perf.append(buf)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ind['Home Game'].replace({1:0}, inplace=True)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  opp_perf=opp_perf.append(ind)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nor['Home Game'].replace({1:0}, inplace=True)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  opp_perf=opp_perf.append(nor)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jax['Home Game'].replace({0:1}, inplace=True)
C:\Users\gandj\AppData\Local\Temp\ipykernel_42608\3293344856.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  opp_perf=opp_perf.append(jax)

,Opponent,Cmp,Att,Cmp%,Avg_Yds,TD,Int,Sk,Def-Rating,Lng,...,Opponent_NYG,Opponent_NYJ,Opponent_OAK,Opponent_PHI,Opponent_PIT,Opponent_SEA,Opponent_SFO,Opponent_TAM,Opponent_TEN,Opponent_WAS
0,ARI,30.00,43.00,69.7700,8.230000,2.000000,1.00,1.000000,5.000000,26.000000,...,0,0,0,0,0,0,0,0,0,0
2,ARI,20.50,32.00,64.4850,10.635000,1.500000,1.50,3.500000,16.000000,45.500000,...,0,0,0,0,0,0,0,0,0,0
4,ATL,17.00,20.00,85.0000,12.710000,3.000000,0.00,0.000000,0.000000,28.000000,...,0,0,0,0,0,0,0,0,0,0
4,ATL,17.00,20.00,85.0000,12.710000,3.000000,0.00,0.000000,0.000000,28.000000,...,0,0,0,0,0,0,0,0,0,0
5,BAL,20.50,37.00,55.9825,14.042500,1.500000,1.25,1.250000,6.750000,45.500000,...,0,0,0,0,0,0,0,0,0,0
7,BAL,23.75,38.75,61.7675,11.042500,1.750000,1.00,1.250000,5.500000,35.750000,...,0,0,0,0,0,0,0,0,0,0
9,BUF,26.00,38.00,68.4200,9.150000,2.000000,0.00,2.000000,5.000000,24.000000,...,0,0,0,0,0,0,0,0,0,0
9,BUF,26.00,38.00,68.4200,9.150000,2.000000,0.00,2.000000,5.000000,24.000000,...,0,0,0,0,0,0,0,0,0,0
10,CAR,18.00,22.00,81.8200,13.220000,1.000000,0.00,1.000000,5.000000,66.000000,...,0,0,0,0,0,0,0,0,0,0
11,CHI,19.00,31.00,61.2900,12.950000,1.000000,0.00,5.000000,16.000000,26.000000,...,0,0,0,0,0,0,0,0,0,0
12,CIN,16.75,25.50,65.6900,16.475000,3.500000,1.00,2.000000,11.750000,43.750000,...,0,0,0,0,0,0,0,0,0,0
14,CIN,18.00,28.00,62.7900,13.886667,1.666667,1.00,0.333333,5.333333,47.666667,...,0,0,0,0,0,0,0,0,0,0
16,CLE,16.00,27.00,59.2600,14.690000,1.000000,1.00,4.000000,19.000000,75.000000,...,0,0,0,0,0,0,0,0,0,0
17,DAL,19.00,30.00,63.3300,8.680000,2.000000,0.00,2.000000,7.000000,16.000000,...,0,0,0,0,0,0,0,0,0,0
20,DEN,24.00,28.00,85.7100,9.580000,2.000000,0.00,0.000000,0.000000,22.000000,...,0,0,0,0,0,0,0,0,0,0
18,DEN,22.50,36.50,61.1750,10.275000,1.500000,0.50,2.000000,7.500000,36.000000,...,0,0,0,0,0,0,0,0,0,0
22,DET,15.00,29.00,51.7200,11.730000,1.000000,2.00,1.000000,10.000000,37.000000,...,0,0,0,0,0,0,0,0,0,0
23,GNB,16.50,28.50,57.7350,9.910000,1.500000,2.50,5.000000,27.000000,29.000000,...,0,0,0,0,0,0,0,0,0,0
24,HOU,29.00,43.00,67.4400,13.690000,1.000000,3.00,0.000000,7.000000,71.000000,...,0,0,0,0,0,0,0,0,0,0
26,HOU,15.50,20.50,75.2400,11.105000,0.500000,0.50,1.500000,9.500000,27.000000,...,0,0,0,0,0,0,0,0,0,0
28,IND,21.00,37.00,56.7600,11.760000,2.000000,2.00,1.000000,8.000000,32.000000,...,0,0,0,0,0,0,0,0,0,0
28,IND,21.00,37.00,56.7600,11.760000,2.000000,2.00,1.000000,8.000000,32.000000,...,0,0,0,0,0,0,0,0,0,0
29,JAX,19.00,29.00,65.5200,13.580000,2.000000,0.00,2.000000,7.000000,27.000000,...,0,0,0,0,0,0,0,0,0,0
29,JAX,19.00,29.00,65.5200,13.580000,2.000000,0.00,2.000000,7.000000,27.000000,...,0,0,0,0,0,0,0,0,0,0
30,KAN,22.00,32.50,68.5800,12.080000,0.500000,1.00,1.500000,8.000000,35.500000,...,0,0,0,0,0,0,0,0,0,0
32,KAN,29.00,42.00,69.0500,10.240000,2.000000,1.00,2.000000,7.000000,38.000000,...,0,0,0,0,0,0,0,0,0,0
36,LAC,22.00,46.00,47.8300,10.820000,1.000000,2.00,5.000000,15.000000,32.000000,...,0,0,0,0,0,0,0,0,0,0
34,LAC,17.00,25.50,64.8850,12.630000,1.000000,0.00,2.000000,9.500000,55.000000,...,0,0,0,0,0,0,0,0,0,0
38,LAR,18.00,36.00,50.0000,10.830000,1.000000,1.00,3.000000,11.000000,30.000000,...,0,0,0,0,0,0,0,0,0,0
39,LVR,12.00,25.00,48.0000,10.170000,0.000000,0.00,0.000000,0.000000,25.000000,...,0,0,0,0,0,0,0,0,0,0
40,MIA,24.00,34.00,70.5900,13.620000,3.000000,1.00,1.000000,6.000000,37.000000,...,0,0,0,0,0,0,0,0,0,0
41,MIN,15.00,33.00,45.4500,10.330000,0.000000,0.00,3.000000,9.000000,24.000000,...,0,0,0,0,0,0,0,0,0,0
42,NOR,12.00,25.00,48.0000,14.170000,1.000000,0.00,3.000000,12.000000,67.000000,...,0,0,0,0,0,0,0,0,0,0
42,NOR,12.00,25.00,48.0000,14.170000,1.000000,0.00,3.000000,12.000000,67.000000,...,0,0,0,0,0,0,0,0,0,0
43,NWE,15.50,26.00,58.4500,8.170000,1.000000,1.00,3.500000,16.500000,22.000000,...,0,0,0,0,0,0,0,0,0,0
44,NYG,20.50,30.50,66.3300,10.680000,1.500000,0.00,1.500000,5.000000,25.500000,...,1,0,0,0,0,0,0,0,0,0
45,NYJ,23.50,44.00,53.5600,13.645000,0.500000,0.50,3.500000,9.500000,58.500000,...,0,1,0,0,0,0,0,0,0,0
47,NYJ,17.00,23.00,73.9100,11.820000,0.000000,0.00,1.000000,4.000000,29.000000,...,0,1,0,0,0,0,0,0,0,0
49,OAK,21.00,41.00,51.2200,14.050000,2.000000,2.00,2.000000,10.000000,59.000000,...,0,0,1,0,0,0,0,0,0,0
50,PHI,12.00,22.00,54.5500,17.000000,0.000000,0.00,3.000000,14.000000,43.000000,...,0,0,0,1,0,0,0,0,0,0
53,PIT,18.00,30.00,60.2000,11.376667,1.000000,0.00,3.000000,10.333333,36.000000,...,0,0,0,0,1,0,0,0,0,0
51,PIT,17.40,31.60,55.3580,11.010000,1.800000,1.20,4.000000,17.800000,32.400000,...,0,0,0,0,1,0,0,0,0,0
57,SEA,22.00,37.00,59.4600,11.320000,1.000000,3.00,0.000000,8.000000,41.000000,...,0,0,0,0,0,1,0,0,0,0
55,SEA,13.00,26.00,50.0000,11.310000,0.000000,1.00,5.000000,23.000000,35.000000,...,0,0,0,0,0,1,0,0,0,0
61,SFO,20.00,36.00,55.5600,10.750000,0.000000,1.00,4.000000,14.000000,32.000000,...,0,0,0,0,0,0,1,0,0,0
59,SFO,8.00,22.00,36.3600,12.500000,0.000000,2.00,4.000000,27.000000,25.000000,...,0,0,0,0,0,0,1,0,0,0
63,TAM,23.00,34.00,67.6500,9.350000,2.000000,0.00,5.000000,15.000000,23.000000,...,0,0,0,0,0,0,0,1,0,0
64,TEN,25.00,33.00,75.7600,13.360000,4.000000,0.00,0.000000,0.000000,75.000000,...,0,0,0,0,0,0,0,0,1,0
66,TEN,25.00,38.00,65.7900,11.400000,1.000000,3.00,5.000000,21.000000,35.000000,...,0,0,0,0,0,0,0,0,1,0
68,WAS,16.00,23.00,69.5700,9.750000,2.000000,0.00,2.000000,9.000000,18.000000,...,0,0,0,0,0,0,0,0,0,1

In [305]:
opp_perf[opp_perf['Opponent']=='BUF']['Home Game']

9    1
9    0
Name: Home Game, dtype: int64

In [306]:
final_model.predict(x_features(bakers_schedule,'TAM',4,opp_perf))[0]

C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(

188.75021754492818

In [307]:
# note, we do not scale the x/input features, because with our model was underfitting
weeks=bakers_schedule[bakers_schedule['Week']!=5]['Week'].astype(int).to_list()
weekperf=[]
for x in weeks:
    weekperf.append(round(final_model.predict(x_features(bakers_schedule,'TAM',x,opp_perf)).item(),0))
print(weekperf)

C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(

[151.0, 226.0, 217.0, 189.0, 176.0, 217.0, 257.0, 374.0, 275.0, 99.0, 242.0, 247.0, 219.0, 160.0, 241.0, 186.0]

C:\Users\gandj\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(

In [308]:
weekperf.append('bye')
weekperf[4]='bye'
weekperf[5]=176.0
weekperf[6]=217.0
weekperf[7]=257.0
weekperf[8]=374.0
weekperf[9]=275.0
weekperf[10]=99.0
weekperf[11]=242.0
weekperf[12]=247.0
weekperf[13]=219.0
weekperf[14]=160.0
weekperf[15]=241.0
weekperf[16]=186.0
weekperf

[151.0,
 226.0,
 217.0,
 189.0,
 'bye',
 176.0,
 217.0,
 257.0,
 374.0,
 275.0,
 99.0,
 242.0,
 247.0,
 219.0,
 160.0,
 241.0,
 186.0]

In [309]:
bakers_schedule['pred_passing']=weekperf
#bakers_schedule['pred'].replace({[176.3705544714429]:'bye'})
bakers_schedule

,Week,Day,Date,Time,Winner/tie,Unnamed: 5,Loser/tie,Unnamed: 7,PtsW,PtsL,YdsW,TOW,YdsL,TOL,RoadTeam,HomeTeam,Home_Game,pred_passing
,,,,,,,,,,,,,,,,,,
1,1.0,Sun,2023-09-10,1:00PM,Tampa Bay Buccaneers,@,Minnesota Vikings,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,MIN,Road Game,151.0
2,2.0,Sun,2023-09-17,1:00PM,Chicago Bears,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,CHI,TAM,Home Game,226.0
3,3.0,Mon,2023-09-25,7:15PM,Philadelphia Eagles,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,PHI,TAM,Home Game,217.0
4,4.0,Sun,2023-10-01,1:00PM,Tampa Bay Buccaneers,@,New Orleans Saints,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,NOR,Road Game,189.0
5,5.0,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye,bye
6,6.0,Sun,2023-10-15,1:00PM,Detroit Lions,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,DET,TAM,Home Game,176.0
7,7.0,Sun,2023-10-22,1:00PM,Atlanta Falcons,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,ATL,TAM,Home Game,217.0
8,8.0,Thu,2023-10-26,8:15PM,Tampa Bay Buccaneers,@,Buffalo Bills,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,BUF,Road Game,257.0
9,9.0,Sun,2023-11-05,1:00PM,Tampa Bay Buccaneers,@,Houston Texans,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,HOU,Road Game,374.0
10,10.0,Sun,2023-11-12,1:00PM,Tennessee Titans,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,TEN,TAM,Home Game,275.0
11,11.0,Sun,2023-11-19,4:05PM,Tampa Bay Buccaneers,@,San Francisco 49ers,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,SFO,Road Game,99.0
12,12.0,Sun,2023-11-26,1:00PM,Tampa Bay Buccaneers,@,Indianapolis Colts,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,IND,Road Game,242.0
13,13.0,Sun,2023-12-03,1:00PM,Carolina Panthers,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,CAR,TAM,Home Game,247.0
14,14.0,Sun,2023-12-10,1:00PM,Tampa Bay Buccaneers,@,Atlanta Falcons,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,ATL,Road Game,219.0
15,15.0,Sun,2023-12-17,1:00PM,Tampa Bay Buccaneers,@,Green Bay Packers,preview,NaN,NaN,NaN,NaN,NaN,NaN,TAM,GNB,Road Game,160.0
16,16.0,Sun,2023-12-24,4:05PM,Jacksonville Jaguars,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,JAX,TAM,Home Game,241.0
17,17.0,Sun,2023-12-31,1:00PM,New Orleans Saints,@,Tampa Bay Buccaneers,preview,NaN,NaN,NaN,NaN,NaN,NaN,NOR,TAM,Home Game,186.0

In [310]:
bakers_schedule.to_csv("Baker's_Schedule.csv")

In [313]:
bakers_schedule.to_excel("Baker's_Schedule.xlsx")